#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

export TERMINAL_SANDBOX_BACKEND="${TERMINAL_SANDBOX_BACKEND:-modal}"
export TB_TRAIN_DATASET="${TB_TRAIN_DATASET:-tb-opus-pass}"
export MINISWE_MAX_TURNS="${MINISWE_MAX_TURNS:-128}"
export MINISWE_MAX_CONSECUTIVE_FORMAT_ERRORS="${MINISWE_MAX_CONSECUTIVE_FORMAT_ERRORS:-1}"
export MINISWE_COMMAND_TIMEOUT="${MINISWE_COMMAND_TIMEOUT:-300}"
export RLLM_SANDBOX_MAX_CPUS="${RLLM_SANDBOX_MAX_CPUS:-0.125}"
export RLLM_SANDBOX_MAX_MEMORY_MB="${RLLM_SANDBOX_MAX_MEMORY_MB:-256}"
export RLLM_MODAL_SANDBOX_CREATE_RPS="${RLLM_MODAL_SANDBOX_CREATE_RPS:-2}"
export RLLM_HARNESS_INSTALL_TIMEOUT_S="${RLLM_HARNESS_INSTALL_TIMEOUT_S:-300}"
export RLLM_HARNESS_RUN_TIMEOUT_S="${RLLM_HARNESS_RUN_TIMEOUT_S:-3000}"
export RLLM_HARNESS_VERIFIER_TIMEOUT_S="${RLLM_HARNESS_VERIFIER_TIMEOUT_S:-300}"
export RLLM_SANDBOX_TIMEOUT_S="${RLLM_SANDBOX_TIMEOUT_S:-3600}"
export RLLM_MODAL_SANDBOX_TIMEOUT_S="${RLLM_MODAL_SANDBOX_TIMEOUT_S:-3600}"

MODEL_PATH="${MODEL_PATH:-Qwen/Qwen3.5-35B-A3B}"
PROJECT_NAME="${PROJECT_NAME:-terminal-rl}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-qwen3p5-35b-a3b-terminal-rl-verl}"
CKPT_DIR="${CKPT_DIR:-checkpoints/${PROJECT_NAME}/${EXPERIMENT_NAME}}"

N_GPUS_PER_NODE="${N_GPUS_PER_NODE:-8}"
TRAIN_NNODES="${TRAIN_NNODES:-2}"
ROLLOUT_NNODES="${ROLLOUT_NNODES:-2}"
ROLLOUT_N="${ROLLOUT_N:-16}"
PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-16}"
TOTAL_EPOCHS="${TOTAL_EPOCHS:-100}"
STALENESS_THRESHOLD="${STALENESS_THRESHOLD:-4.0}"
TRIGGER_PARAMETER_SYNC_STEP="${TRIGGER_PARAMETER_SYNC_STEP:-1}"
INFER_TP="${INFER_TP:-2}"
SP_SIZE="${SP_SIZE:-4}"
EP_SIZE="${EP_SIZE:-2}"
GPU_MEM_UTIL="${GPU_MEM_UTIL:-0.85}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-131072}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-16384}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-131072}"
ACTOR_MAX_TOKEN_LEN_PER_GPU=$(( MAX_MODEL_LEN / SP_SIZE ))

python -u train.py \
    rllm/backend=verl \
    +model.name="${MODEL_PATH}" \
    model_engine=veomni \
    actor_rollout_ref.model.path="${MODEL_PATH}" \
    actor_rollout_ref.model.use_remove_padding=true \
    actor_rollout_ref.model.use_fused_kernels=true \
    actor_rollout_ref.model.enable_gradient_checkpointing=true \
    actor_rollout_ref.actor.veomni.enable_fsdp_offload=true \
    actor_rollout_ref.actor.veomni.enable_full_shard=true \
    actor_rollout_ref.actor.veomni.ulysses_parallel_size="${SP_SIZE}" \
    actor_rollout_ref.actor.veomni.expert_parallel_size="${EP_SIZE}" \
    actor_rollout_ref.actor.veomni.attn_implementation=flash_attention_3 \
    actor_rollout_ref.actor.veomni.moe_implementation=fused_triton \
    actor_rollout_ref.actor.veomni.cross_entropy_loss_implementation=liger_kernel \
    actor_rollout_ref.actor.optim.optimizer=adamw \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_scheduler_type=constant \
    actor_rollout_ref.actor.optim.lr_warmup_steps=0 \
    actor_rollout_ref.actor.optim.clip_grad=1.0 \
    actor_rollout_ref.actor.ppo_epochs=1 \
    actor_rollout_ref.actor.use_kl_loss=false \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.use_rollout_log_probs=true \
    actor_rollout_ref.actor.clip_ratio_c=1.0e9 \
    actor_rollout_ref.actor.use_dynamic_bsz=true \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu="${ACTOR_MAX_TOKEN_LEN_PER_GPU}" \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=true \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu="${ACTOR_MAX_TOKEN_LEN_PER_GPU}" \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.mode=async \
    actor_rollout_ref.rollout.tensor_model_parallel_size="${INFER_TP}" \
    actor_rollout_ref.rollout.gpu_memory_utilization="${GPU_MEM_UTIL}" \
    actor_rollout_ref.rollout.max_model_len="${MAX_MODEL_LEN}" \
    actor_rollout_ref.rollout.calculate_log_probs=true \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=true \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu="${ACTOR_MAX_TOKEN_LEN_PER_GPU}" \
    actor_rollout_ref.rollout.checkpoint_engine.update_weights_bucket_megabytes=1024 \
    actor_rollout_ref.rollout.multi_turn.enable=true \
    rllm.data.train_batch_size=1 \
    rllm.data.val_batch_size=-1 \
    rllm.data.max_prompt_length="${MAX_PROMPT_LENGTH}" \
    rllm.data.max_response_length="${MAX_RESPONSE_LENGTH}" \
    data.filter_overlong_prompts=true \
    data.truncation=error \
    rllm.rollout.n="${ROLLOUT_N}" \
    rllm.rollout.train.temperature=1.0 \
    rllm.rollout.train.top_p=1.0 \
    rllm.compact_filtering.enable=true \
    'rllm.compact_filtering.mask_termination_reasons=[max_prompt_length_exceeded,max_turns_exceeded,timeout,unknown,error,agent_setup_timeout,env_start_timeout,verifier_timeout,grading_error,sandbox_error,model_error]' \
    rllm.algorithm.adv_estimator=grpo \
    rllm.algorithm.norm_adv_by_std_in_grpo=false \
    rllm.algorithm.kl_beta=0.0 \
    rllm.algorithm.router_replay=R3 \
    rllm.algorithm.loss_fn=dppo_tv \
    rllm.algorithm.loss_agg_mode=token-mean \
    rllm.algorithm.eps_clip=0.1 \
    rllm.algorithm.eps_clip_high=0.1 \
    rllm.algorithm.rollout_correction.bypass_mode=true \
    rllm.algorithm.rollout_correction.tis_mode=null \
    rllm.async_training.enable=true \
    rllm.async_training.mini_batch_size="${PPO_MINI_BATCH_SIZE}" \
    rllm.async_training.fwd_bwd_group_size="${PPO_MINI_BATCH_SIZE}" \
    rllm.async_training.staleness_threshold="${STALENESS_THRESHOLD}" \
    rllm.async_training.trigger_parameter_sync_step="${TRIGGER_PARAMETER_SYNC_STEP}" \
    rllm.async_training.partial_rollout=true \
    rllm.workflow.n_parallel_tasks=256 \
    rllm.workflow.raise_on_error=false \
    rllm.rejection_sample.min_trajs_per_group=4 \
    rllm.rejection_sample.filter_uniform_groups=true \
    rllm.gateway.port=9200 \
    rllm.gateway.num_workers=8 \
    rllm.gateway.cumulative_token_mode=true \
    rllm.gateway.renderer_family=qwen3.5 \
    trainer.nnodes="${TRAIN_NNODES}" \
    trainer.n_gpus_per_node="${N_GPUS_PER_NODE}" \
    trainer.default_local_dir="${CKPT_DIR}" \
    trainer.default_hdfs_dir=null \
    trainer.resume_mode=disable \
    rollout.nnodes="${ROLLOUT_NNODES}" \
    rollout.n_gpus_per_node="${N_GPUS_PER_NODE}" \
    rllm.trainer.total_epochs="${TOTAL_EPOCHS}" \
    rllm.trainer.val_before_train=true \
    rllm.trainer.test_freq=25 \
    rllm.trainer.save_freq=25 \
    rllm.episode_logging.log_episodes=false \
    rllm.episode_logging.log_backend_batches=false \
    rllm.trainer.logger='[console,wandb]' \
    rllm.trainer.project_name="${PROJECT_NAME}" \
    rllm.trainer.experiment_name="${EXPERIMENT_NAME}" \
    "$@"
