# Ruff configuration for DeepResearch
# Exclude original reference files from linting
exclude = [
    "original/react_agent_original.py",
    "original/tool_file_original.py",
    "original/tool_search_original.py"
]